name: hsma4_forecast9b_win
channels:
  - conda-forge
dependencies:
  - ipywidgets=7.6.5
  - jupyterlab=3.2.4
  - jupyterlab-plotly-extension=1.0.0
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.0.1
  - plotly=5.4.0
  - prophet=1.0.1
  - python=3.8.8
  - scipy=1.7.3
  - seaborn=0.11.2
  - pip:
    - forecast-tools==0.1.6
    - scikit-learn==1.0.1
