name: hsma_forecast2
channels:
  - defaults
  - conda-forge
dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=2.1.2
  - matplotlib=3.2.1
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.1.3
  - pip=20.0.2
  - plotly=4.13.0
  - python=3.7.7
  - scipy=1.4.1
  - seaborn=0.10.0
  - tensorflow=2.0.0
  - pip:
    - scikit-learn==0.23.0
    - fbprophet==0.7.1
    - forecast-tools==0.1.5
